# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cb69bad95e26a72db0a7d3b4ecbf3675d66f7a543f2d3b409f078aded70c9ff8f7c02be3cf9a2b7c1b14d54279b5ede632ce328bcb20c451222174681d6f805

test:
  secret_key_base: ce6b7b6d520f1840b54b98d8ce0ca7c03fb9e0f1e9876df56d14958c68bd37fe92dc14f3ec52d3a9a3fb6d4924584426d49eacf63a64a0a0dbb738b442a072ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ce6b7b6d520fdg1840b5agsdgh4b98d8ce0ca7c03fb9e0f1e9876df56d14958c68bghkghkd37fe92dc14f3ec52d3a9a3fb6d4924584426d49eacf63a64a0a0dbb738b442a072eefg